### PR TITLE
Save the results of the shuffle to a playlist on demand

### PR DESCRIPTION
**Pull request by UnderwaterMug**
If a user has liked a particular queue generated by the app, he or she can save this queue to a playlist called 'True Shuffle Playlist + date'.

### CODE REVIEW

**Comment by kartikk221** [comment]
Hey, I just comitted the prettier configuration for the proejct to the repository, could you pull and re-save your changes so your changes become formatted the same way and the diffs become mroe accurate.

Also, in the save to playlist function, you seem to store the created playlist in a variable called `playlist` but this variable does not seem to be initiaized locally hence it would be set in the global scope thus it would be better to initialize the playlist variable locally before the try...catch to ensure there is no data expansion outside of the scope. Reference: https://github.com/kartikk221/spotify-true-shuffle/blob/1a18f93f1f2e337e30ba1604fb76503ad66bab71/assets/js/main.js#L230

**Comment by UnderwaterMug** [comment]
Imported the prettier configuration, 
and for the `playlist` variable it was really a simple case of adding `let playlist;` at the start of the function

**Comment by UnderwaterMug** [comment]
Wait, the `index.html` didn't formatted correctly

**Comment by UnderwaterMug** [comment]
Okay, now it's formatted correctly

**Review by kartikk221 — APPROVED** [review]

**Pull request merged**
